services:
  postgres:
    image: postgres:15
    container_name: english_learning_postgres
    environment:
      POSTGRES_DB: english_learning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: english_learning_api
    depends_on:
      - postgres
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python -m spacy download en_core_web_sm &&
             python -c 'import nltk; nltk.download(\"wordnet\"); nltk.download(\"omw-1.4\")' &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local